### ISSUE TITLE
Aroma Updater Potentially Installed A Corrupted Version of the EnvironmentLoader after installing Aroma Beta-21

### ISSUE THREAD

**Issue by Jediweirdo** [wiiu-env/AromaUpdater#22]
Not much to say other than to tell you what I know:

### Information Gathered After "Testing"
- This is an updater problem, not a problem with Beta-21 itself. If you go on aroma.foryour.cafe, that aroma version works fine and doesn't have this issue.
- This problem is exclusive to Aroma and probably any custom environments that aren't hardcoded into the environmentloader like Tiramisu (or at least I think Tiramisu is hardcoded into the Environmentloader? Whatever the case may be, Tiramisu isn't affected by this bug)
- The problem doesn't seem to be stemming from the autoboot files, like `99_autoboot.rpx` or `autoboot.cfg`
- (unsurprisingly) crashed the Wii U no matter what option was chosen- the Wii U Menu, the vWii System Menu, or the vWii Homebrew Launcher. The Wii U menu boot loops, and the vWii-related-things have the Wii U fade to black and start making noises that could be found in the next _Alien_ movie

### In the events following this entire ordeal...
- I booted up AromaUpdater in the Aroma Environment
- Chose a few extra files to update that was already pre-existing on my SD card (Wiiload, FTPiiU, StreamingService plugin, and maybe 1 other)
- Installed a plugin that was not on my system (USBLogger)
- Went to confirm the update, but most of the files I picked weren't there, and I believe it had to install 7 files in all (take that tentative number with a grain of salt-- It's been a while since this issue first started)
- Thought nothing of it and confirmed (I already had the files on my SD card, and it said that they were up to date, so it made sense to me for why they didn't show up)
- AromaUpdater did its thing and finished with no errors
- Prompts me to restart my Wii U, and the issue arises

### Final Remarks
This information probably isn't very beneficial when it comes to debugging (sorry about that), so I'll link my "Infected" wiiu file in this issue (I would attach it, but it's too big :p). I wish I had a copy of what it looked like before this happened, but sadly, I didn't think that far ahead. I'm not even sure if this issue affects the vast majority of people since it's very simple to solve (redownload aroma), but if you're as curious as I am about what could have caused this, good luck! Tell me how it goes and what the issue was (if you find one) because I'm very curious about what could have gone wrong. Cheers!

Wii U FOLDER LINK: https://mega.nz/file/7jZCXQJR 

Password: nswBbchIT5mirgxT2MNaEf11NadbZ-2yYYLWelUcQB4

Edit (12:21MST, 7/7/24): Added password to the mega drive and fixed some grammar-related problems

**Comment by Maschell** [comment]
The link is password protected

**Comment by Maschell** [comment]
The Updater does not touch the autoboot.cfg at all.

**Comment by Jediweirdo** [comment]
> The link is password protected

Sorry about that-- the key for it is here: nswBbchIT5mirgxT2MNaEf11NadbZ-2yYYLWelUcQB4

I also apologize for how big my wiiu file is-- I didn't want to delete something that could be important to the issue accidentally, so I just threw my entire wiiu folder on mega 😅

**Comment by Jediweirdo** [comment]
> The Updater does not touch the autoboot.cfg at all.

Yeah, I don't think the problem is stemming from `autoboot.cfg` or `99_autoboot.rpx`. Even if you delete/regenerate autoboot.cfg, the problem is still there. Maybe it's an issue with how the `autoboot.cfg` is getting read internally? I'm not much of a coder, but that's the only other thing I can think of. At some point, I also thought it may be because I had ISFSHax installed, but after I reinstalled Aroma everything strangely started working fine. That's the only reason why I think that it might be a problem with the updater rather than Aroma itself-- this problem only introduced itself after I updated Aroma through the updater. I'm just as stumped as you are lol

**Comment by Maschell** [comment]
By looking at the .zip and doing some quick tests it seems like these issue were coming from the SNTP-Client.wps, not the aroma update

**Comment by Jediweirdo** [comment]
Yep, you're right-- SNTP Client was the issue. Deleting the plugins folder was one of the first things I tried, but I idiotically deleted `SD://wiiu/plugins` instead of `SD://wiiu/enviroments/aroma/plugins`. Sorry for wasting your time man...
