### ISSUE TITLE
Cert verify failed: BADCERT_FUTURE error when checking for updates

### ISSUE THREAD

**Issue by f0rmwk** [wiiu-env/AromaUpdater#23]
When attempting to check for updates using Aroma Updater, I encountered an error indicating that the certificate verification failed due to a "BADCERT_FUTURE" error. Below are the details of the error message:

`An error has happened:
Failed to download the latest version information. libcurl error code 60 (Cert verify failed: BADCERT_FUTURE)
Make sure your console has the correct date.
Date of the console: Wed Jul 31 19:29:15 2024`

Steps to Reproduce:

- Open Aroma Updater.
- Click the 'A' button to check for updates.
- Observe the error message.

Expected Behavior:
The updater should successfully check for and download the latest version information.

Actual Behavior:
The updater fails with a certificate verification error.

Additional Information:

- The console date is correctly set to the current date using Wii U Time Sync.
- The error message suggests a certificate validity issue, even though the date is accurate.

Environment:
Aroma Updater Version: v0.2.3

**Comment by Maschell** [comment]
Did you try again today?

**Comment by f0rmwk** [comment]
Haven't yet. I'll try again tonight. Thanks!

**Comment by Maschell** [comment]
Context: The SSL certificated has been renewed  last night ("Wed, 31 Jul 2024 20:42:40 GMT" to be specific). Depending on your timezone the console might detect the certificate as invalid. In you case you tried at 19:29, but the cert started at 20:42. 

Not sure if I can do anything about this tbh.

**Comment by f0rmwk** [comment]
Ah, I see. I'll check again. Thanks for your help.

**Comment by f0rmwk** [comment]
Tried it again yesterday and it worked! Thanks for your help!
