### ISSUE TITLE
Updater v0.2 want to update to v0.2

### ISSUE THREAD

**Issue by Kugane** [wiiu-env/AromaUpdater#8]
I updated manually to the new version and checked after that for updates.

Looks like it didnt know its own version.

![WhatsApp Bild 2023-01-26 um 18 22 47](https://user-images.githubusercontent.com/14034601/214905652-5f66f82c-ff2f-4f8e-9cba-a2b661e8eb20.jpg)
![WhatsApp Bild 2023-01-26 um 18 22 53](https://user-images.githubusercontent.com/14034601/214905659-d9d1e655-cb88-46d6-9270-d761454a4f41.jpg)

**Comment by Kugane** [comment]
I installed it again and now it works. Didnt know what happend

**Comment by Maschell** [comment]
You updated manually faster than I could release the new Aroma Beta. The Updater will always check https://aroma.foryour.cafe/ for latest released, not Github.

The error when checking the version should not happen though, but I've already fixed it. The next time it should tell you it's newer than expected
